apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: steep-dog-python 
  janus-idp.io/tekton: steep-dog-python
  backstage.io/kubernetes-id: steep-dog-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: steep-dog-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  