apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: steep-dog-python-gitops
  description: This is GitOps manifest for steep-dog-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: steep-dog-python
    janus-idp.io/tekton: steep-dog-python 
    backstage.io/kubernetes-id: steep-dog-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:steep-dog-python
